name: python-django-cyph3r-build
on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest   
        services:
          redis:
            image: redis:alpine
            ports:
              - 6379:6379
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install app OS dependencies
              run: sudo apt-get update && sudo apt-get install -y gnupg libmagic1
            
            - name: Install app python dependencies
              run: |
                python -m pip install --no-cache-dir -r requirements.txt

            - name: Generate Django Secret Key
              run: |
                    DJANGO_DEV_SECRET_KEY=$(python3 -c 'import django.utils.crypto; print(django.utils.crypto.get_random_string(50, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-="))')
                    echo "DJANGO_DEV_SECRET_KEY=$DJANGO_DEV_SECRET_KEY" >> $GITHUB_ENV
            

            - name: Run migrations
              run: python manage.py migrate --noinput
            
            - name: Create Media Folder
              run: mkdir -p media

            - name: Run tests
              run: pytest --maxfail=1 --disable-warnings -q