name: python-django-cyph3r-build
on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Print folders
              run: |
                echo "Folders in the repository:"
                ls -d */